### ISSUE TITLE
Build vulnerability toleration into image scan

### ISSUE THREAD

**Issue by mccbryan3** [CrowdStrike/container-image-scan#24]
I would like to see if we can build tolerations for vulnerabilities into the cs_scanimage.py script.

The idea is that we count vulnerabilities based on severity in the code and only exit non-zero if the count does not meet this criteria. The idea would be to count Low, Medium, High and Critical and exit non-zero based on input arguments.

As an example the below would only fail if the count of High vulnerabilities was greater than or equal to 3.

cs_scanimage.py  -hv 3

There should also be a way to allow for the script to return zero in any circumstance. At least perhaps we could use a high number on Critical to accomplish this..

i.e. cs_scanimage.py  -hv 99

Or something to this extent.

**Comment by isimluk** [comment]
+1 :+1: 

I would propose to have score instead of the return value. Then, for each deficiency we would up the score based on the severity (think of +500 for critical flaw, +100 for high, +10 for medium, etc.). Such scoring would allow users to define their own acceptable score cut-off.

**Comment by mccbryan3** [comment]
I think this is reasonable and may circumvent some of the complexity with an and operator for combining mediums highs and criticals. I think the scoring proposed looks like a great start.
