### ISSUE TITLE
podman.errors.exceptions.APIError: 400 Client Error: Bad Request 

### ISSUE THREAD

**Issue by Epoxboy** [CrowdStrike/container-image-scan#40]
We're using script for image scanning. It's executed on pipeline agent( RedHat 8.5 with podman 3.3.1) and got following error:

podman.errors.exceptions.APIError: 400 Client Error: Bad Request (error pushing image "container-upload.us-1.crowdstrike.com/docker.io/library/python:slim": trying to reuse blob sha256:fd95118eade99a75b949f634a0994e0f0732ff18c2573fabdfc8d4f95b092f0e at destination: unable to retrieve auth token: invalid username/password: unauthorized)

I've attached details in this txt file for your reference.
[27.txt](https://github.com/CrowdStrike/container-image-scan/files/8801213/27.txt)

I've had a quick look, it seems a missing "auth_config" parameter in your "container_push" method?? 
https://github.com/CrowdStrike/container-image-scan/blob/5258ea8b242173e47954bd723d6f7d1b71bda949/cs_scanimage.py#L89

podman-py lib ref:
https://github.com/containers/podman-py/blob/a174c43ea07c960cc11af8444ad7143094749246/podman/domain/images_manager.py#L187

Thanks!

BTW:
The client id and secret are available and have been verified.

**Comment by redhatrises** [comment]
Hello,

Thank you for reporting this. Can you provide the version of podman and python3-podman that you are using?

**Comment by Epoxboy** [comment]
> 
RedHat 8.5 with podman 3.3.1
python3-podman: podman (3.2.0)

**Comment by Epoxboy** [comment]
And in order to rule out potential podman service configuration issue on above pipeline agent, I tested the script on an Ubuntu server and got same error. Versions info is as following:
Ubuntu 20.04.4 LTS with podman 3.4.2
 python3-podman: podman (4.0.0)

And in both above cases, podman login and podman push are working fine.

**Comment by Epoxboy** [comment]
I've had a look at podman-py latest release 4.0.0, seems like auth_config is not implemented yet... that should be the reason of causing this error, just my thought anyway, please check and confirm.
<img width="377" alt="image" src="https://user-images.githubusercontent.com/20849673/172041054-1c47d971-543f-424c-9965-dccdd2064e63.png">

**Comment by redhatrises** [comment]
Hello,

Please make sure that both podman and python3-podman are at version 4.

**Comment by redhatrises** [comment]
Closing as there isn't any further information provided on this. Please re-open with more info around podman versioning.
