### ISSUE TITLE
load_config() got an unexpected keyword argument 'config_dict'

### ISSUE THREAD

**Issue by Johnnydtech** [CrowdStrike/container-image-scan#41]
+ '[' '!' -d container-image-scan ']'
+ pip3 install docker
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: docker in /var/lib/jenkins/.local/lib/python3.7/site-packages (5.0.3)
Requirement already satisfied: requests!=2.18.0,>=2.14.2 in /var/lib/jenkins/.local/lib/python3.7/site-packages (from docker) (2.26.0)
Requirement already satisfied: websocket-client>=0.32.0 in /var/lib/jenkins/.local/lib/python3.7/site-packages (from docker) (1.1.0)
Requirement already satisfied: idna<4,>=2.5; python_version >= "3" in /var/lib/jenkins/.local/lib/python3.7/site-packages (from requests!=2.18.0,>=2.14.2->docker) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /var/lib/jenkins/.local/lib/python3.7/site-packages (from requests!=2.18.0,>=2.14.2->docker) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in /var/lib/jenkins/.local/lib/python3.7/site-packages (from requests!=2.18.0,>=2.14.2->docker) (2021.5.30)
Requirement already satisfied: charset-normalizer~=2.0.0; python_version >= "3" in /var/lib/jenkins/.local/lib/python3.7/site-packages (from requests!=2.18.0,>=2.14.2->docker) (2.0.3)
+ python3 container-image-scan/cs_scanimage.py
ERROR   Unknown error
Traceback (most recent call last):
  File "container-image-scan/cs_scanimage.py", line 355, in main
    client = docker.from_env()
  File "/var/lib/jenkins/.local/lib/python3.7/site-packages/docker/client.py", line 10
![Screen Shot 2022-06-22 at 4 57 42 PM](https://user-images.githubusercontent.com/36245619/175134900-13ca2efe-e061-4ffa-a9f0-981cbda52866.png)
1, in from_env
    **kwargs_from_env(**kwargs)
  File "/var/lib/jenkins/.local/lib/python3.7/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/var/lib/jenkins/.local/lib/python3.7/site-packages/docker/api/client.py", line 132, in __init__
    config_dict=self._general_configs, credstore_env=credstore_env,
TypeError: load_config() got an unexpected keyword argument 'config_dict'

**Comment by Johnnydtech** [comment]
1. Do you have more than 1 python interpreter installed?
- The server has python version 2.7.18 and python 3.7.10
2. Do you have docker-py and docker python modules installed?
- It only currently has docker-5.0.3
3. Is the python environment being called correctly?
- "Python3 container-image-scan/cs_scanimage.py" is how it is being called and works on the server 
5. What does pip3 freeze | grep docker return?
- docker==5.0.3

**Comment by Johnnydtech** [comment]
On the image scan example repo, the "jenkinsfile" shows to install docker-py, after uninstalling both and updating docker it seemed to have worked. Please update the jenkinsfile
![Screen Shot 2022-06-24 at 10 57 08 AM](https://user-images.githubusercontent.com/36245619/175562435-5493d13f-ccd2-48f9-9aee-002b4dcde563.png)

**Comment by redhatrises** [comment]
Glad it is fixed. Closing as this is an environment issue. For context, see https://github.com/docker/docker-py/issues/1916
